### ISSUE TITLE
prada-frame

### ISSUE THREAD

**Issue by ahdee** [crazyhottommy/PRADA_pipeline_Verhaak_lab#1]
Hi when testing for framness I often get "not-classified" - is there anyway to fix this?  Is this because the input gene names are not recognize?  Thank you! 
Ahdee

**Comment by crazyhottommy** [comment]
Hi,

I am not a maintainer of PRADA. please contact Siyuan Zheng https://mdanderson.influuent.utsystem.edu/en/persons/siyuan-zheng  if you have any questions.

Thanks,
Tommy

**Comment by ahdee** [comment]
thanks I will do that.
